<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class DocumentRequest extends Model
{
    protected $fillable = [
        'reference_number',
        'user_id',
        'student_number',
        'full_name',
        'contact_number',
        'course_program',
        'year_level',
        'section',
        'total_fee',
        'payment_method',
        'status',
        'remarks',
        'claiming_number',
        'appointment_id',
        'processed_by',
    ];

    protected $casts = [
        'total_fee' => 'decimal:2',
    ];

    // -------------------------------------------------------------------------
    // RELATIONSHIPS
    // -------------------------------------------------------------------------

    /**
     * The student who submitted this request.
     * Usage: $request->student->name
     */
    public function student()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    /**
     * The registrar who processed this request.
     * Usage: $request->processedBy->name
     */
    public function processedBy()
    {
        return $this->belongsTo(User::class, 'processed_by');
    }

    /**
     * All the individual document items in this request (e.g. 1 COE + 2 COG).
     * Usage: $request->items — returns a collection of DocumentRequestItem models.
     */
    public function items()
    {
        return $this->hasMany(DocumentRequestItem::class);
    }

    /**
     * The payment proof uploaded by the student (GCash/Bank only).
     * Usage: $request->paymentProof
     * Returns null for cash payments or before the student uploads.
     */
    public function paymentProof()
    {
        return $this->hasOne(PaymentProof::class);
    }

    /**
     * The official receipt generated by the cashier after payment is confirmed.
     * Usage: $request->officialReceipt
     */
    public function officialReceipt()
    {
        return $this->hasOne(OfficialReceipt::class);
    }

    /**
     * The pickup appointment for this request (set when student books a slot).
     * Usage: $request->appointment
     */
    public function appointment()
    {
        return $this->hasOne(Appointment::class);
    }

    /**
     * Full history of every status change for this request.
     * Usage: $request->statusLogs — returns in creation order.
     */
    public function statusLogs()
    {
        return $this->hasMany(StatusLog::class)->orderBy('created_at');
    }

    // -------------------------------------------------------------------------
    // HELPER METHODS
    // -------------------------------------------------------------------------

    /**
     * Whether the student can still upload or re-upload a payment proof.
     * Rules: status must be payment_uploaded or payment_rejected,
     * AND the cashier must not have acted yet (verified_at is null).
     *
     * Usage: if ($request->canReupload()) { ... }
     */
    public function canReupload(): bool
    {
        return in_array($this->status, ['payment_uploaded', 'payment_rejected'])
            && is_null($this->paymentProof?->verified_at);
    }

    /**
     * Whether the student can cancel this request.
     * Only pending requests can be cancelled.
     */
    public function canCancel(): bool
    {
        return $this->status === 'pending';
    }

    /**
     * Human-readable status label for display in Blade views.
     * Usage: $request->statusLabel()
     */
    public function statusLabel(): string
    {
        return match($this->status) {
            'pending'              => 'Pending',
            'payment_method_set'   => 'Payment Method Set',
            'payment_uploaded'     => 'Payment Uploaded',
            'payment_verified'     => 'Payment Verified',
            'payment_rejected'     => 'Payment Rejected',
            'processing'           => 'Processing',
            'ready_for_pickup'     => 'Ready for Pickup',
            'received'             => 'Received',
            'cancelled'            => 'Cancelled',
            default                => ucfirst($this->status),
        };
    }

    /**
     * Bootstrap CSS badge class for each status — used in Blade to color the badge.
     * Usage: <span class="badge {{ $request->statusBadgeClass() }}">
     */
    public function statusBadgeClass(): string
    {
        return match($this->status) {
            'pending'              => 'bg-warning text-dark',
            'payment_method_set'   => 'bg-primary',
            'payment_uploaded'     => 'bg-warning text-dark',
            'payment_verified'     => 'bg-success',
            'payment_rejected'     => 'bg-danger',
            'processing'           => 'bg-secondary',
            'ready_for_pickup'     => 'bg-success',
            'received'             => 'bg-dark',
            'cancelled'            => 'bg-light text-muted',
            default                => 'bg-secondary',
        };
    }
}
